return {
	"pwntester/octo.nvim",
	dependencies = {
		"nvim-lua/plenary.nvim",
		"nvim-telescope/telescope.nvim",
		"nvim-tree/nvim-web-devicons",
		"sindrets/diffview.nvim",
	},
	cmd = "Octo",
	keys = {
		{ "<leader>gi", "<cmd>Octo issue list<cr>", desc = "List issues" },
		{ "<leader>gI", "<cmd>Octo issue create<cr>", desc = "Create issue" },
		{ "<leader>gp", "<cmd>Octo pr list<cr>", desc = "List PRs" },
		{ "<leader>gP", "<cmd>Octo pr create<cr>", desc = "Create PR" },
		{ "<leader>gr", "<cmd>Octo repo list<cr>", desc = "List repos" },
		{ "<leader>gs", "<cmd>Octo search<cr>", desc = "Search issues/PRs" },
	},
	config = function()
		require("octo").setup({
			use_local_fs = true,
			use_diffview = true,
			enable_builtin = true,
			default_remote = { "upstream", "origin" },
			default_to_resolve_thread = false,
			default_merge_method = "squash",
			ssh_aliases = {},
			picker = "telescope",
			picker_config = {
				use_emojis = false,
				mappings = {
					open_in_browser = { lhs = "<C-b>", desc = "open issue in browser" },
					copy_url = { lhs = "<C-y>", desc = "copy url to system clipboard" },
					checkout_pr = { lhs = "<C-o>", desc = "checkout pull request" },
					merge_pr = { lhs = "<C-r>", desc = "merge pull request" },
				},
			},
			comment_icon = "▎",
			outdated_icon = "󰅒 ",
			resolved_icon = " ",
			reaction_viewer_hint_icon = " ",
			user_icon = " ",
			timeline_marker = " ",
			timeline_indent = 2,
			right_bubble_delimiter = "",
			left_bubble_delimiter = "",
			github_hostname = "",
			snippet_context_lines = 4,
			gh_cmd = "gh",
			gh_env = {},
			timeout = 5000,
			ui = {
				use_signcolumn = true,
			},
			issues = {
				order_by = {
					field = "CREATED_AT",
					direction = "DESC",
				},
			},
			pull_requests = {
				order_by = {
					field = "CREATED_AT",
					direction = "DESC",
				},
				always_select_remote_on_create = false,
			},
			file_panel = {
				size = 10,
				use_icons = true,
			},
			mappings = {
				issue = {
					close_issue = { lhs = "<leader>ic", desc = "close issue" },
					reopen_issue = { lhs = "<leader>io", desc = "reopen issue" },
					list_issues = { lhs = "<leader>il", desc = "list open issues" },
					reload = { lhs = "<C-r>", desc = "reload issue" },
					open_in_browser = { lhs = "<C-b>", desc = "open issue in browser" },
					copy_url = { lhs = "<C-y>", desc = "copy url to clipboard" },
					add_assignee = { lhs = "<leader>aa", desc = "add assignee" },
					remove_assignee = { lhs = "<leader>ad", desc = "remove assignee" },
					create_label = { lhs = "<leader>lc", desc = "create label" },
					add_label = { lhs = "<leader>la", desc = "add label" },
					remove_label = { lhs = "<leader>ld", desc = "remove label" },
					goto_issue = { lhs = "<leader>gi", desc = "navigate to issue" },
					add_comment = { lhs = "<leader>ca", desc = "add comment" },
					delete_comment = { lhs = "<leader>cd", desc = "delete comment" },
					react_hooray = { lhs = "<leader>rp", desc = "add/remove tada reaction" },
					react_heart = { lhs = "<leader>rh", desc = "add/remove heart reaction" },
					react_eyes = { lhs = "<leader>re", desc = "add/remove eyes reaction" },
					react_thumbs_up = { lhs = "<leader>r+", desc = "add/remove +1 reaction" },
					react_thumbs_down = { lhs = "<leader>r-", desc = "add/remove -1 reaction" },
					react_rocket = { lhs = "<leader>rr", desc = "add/remove rocket reaction" },
					react_laugh = { lhs = "<leader>rl", desc = "add/remove laugh reaction" },
					react_confused = { lhs = "<leader>rc", desc = "add/remove confused reaction" },
				},
				pull_request = {
					checkout_pr = { lhs = "<leader>po", desc = "checkout PR" },
					merge_pr = { lhs = "<leader>pm", desc = "merge PR" },
					squash_and_merge_pr = { lhs = "<leader>psm", desc = "squash and merge PR" },
					rebase_and_merge_pr = { lhs = "<leader>prm", desc = "rebase and merge PR" },
					list_commits = { lhs = "<leader>pc", desc = "list PR commits" },
					list_changed_files = { lhs = "<leader>pf", desc = "list PR changed files" },
					show_pr_diff = { lhs = "<leader>pd", desc = "show PR diff" },
					add_reviewer = { lhs = "<leader>va", desc = "add reviewer" },
					remove_reviewer = { lhs = "<leader>vd", desc = "remove reviewer" },
					close_issue = { lhs = "<leader>ic", desc = "close PR" },
					reopen_issue = { lhs = "<leader>io", desc = "reopen PR" },
					list_issues = { lhs = "<leader>il", desc = "list open issues" },
					reload = { lhs = "<C-r>", desc = "reload PR" },
					open_in_browser = { lhs = "<C-b>", desc = "open PR in browser" },
					copy_url = { lhs = "<C-y>", desc = "copy url to clipboard" },
					goto_file = { lhs = "gf", desc = "go to file" },
					add_assignee = { lhs = "<leader>aa", desc = "add assignee" },
					remove_assignee = { lhs = "<leader>ad", desc = "remove assignee" },
					create_label = { lhs = "<leader>lc", desc = "create label" },
					add_label = { lhs = "<leader>la", desc = "add label" },
					remove_label = { lhs = "<leader>ld", desc = "remove label" },
					goto_issue = { lhs = "<leader>gi", desc = "navigate to issue" },
					add_comment = { lhs = "<leader>ca", desc = "add comment" },
					delete_comment = { lhs = "<leader>cd", desc = "delete comment" },
					react_hooray = { lhs = "<leader>rp", desc = "add/remove tada reaction" },
					react_heart = { lhs = "<leader>rh", desc = "add/remove heart reaction" },
					react_eyes = { lhs = "<leader>re", desc = "add/remove eyes reaction" },
					react_thumbs_up = { lhs = "<leader>r+", desc = "add/remove +1 reaction" },
					react_thumbs_down = { lhs = "<leader>r-", desc = "add/remove -1 reaction" },
					react_rocket = { lhs = "<leader>rr", desc = "add/remove rocket reaction" },
					react_laugh = { lhs = "<leader>rl", desc = "add/remove laugh reaction" },
					react_confused = { lhs = "<leader>rc", desc = "add/remove confused reaction" },
				},
				review_thread = {
					goto_issue = { lhs = "<leader>gi", desc = "navigate to issue" },
					add_comment = { lhs = "<leader>ca", desc = "add comment" },
					add_suggestion = { lhs = "<leader>sa", desc = "add suggestion" },
					delete_comment = { lhs = "<leader>cd", desc = "delete comment" },
					next_comment = { lhs = "]c", desc = "go to next comment" },
					prev_comment = { lhs = "[c", desc = "go to previous comment" },
					select_next_entry = { lhs = "]q", desc = "move to next changed file" },
					select_prev_entry = { lhs = "[q", desc = "move to previous changed file" },
					select_first_entry = { lhs = "[Q", desc = "move to first changed file" },
					select_last_entry = { lhs = "]Q", desc = "move to last changed file" },
					close_review_tab = { lhs = "<C-c>", desc = "close review tab" },
					react_hooray = { lhs = "<leader>rp", desc = "add/remove tada reaction" },
					react_heart = { lhs = "<leader>rh", desc = "add/remove heart reaction" },
					react_eyes = { lhs = "<leader>re", desc = "add/remove eyes reaction" },
					react_thumbs_up = { lhs = "<leader>r+", desc = "add/remove +1 reaction" },
					react_thumbs_down = { lhs = "<leader>r-", desc = "add/remove -1 reaction" },
					react_rocket = { lhs = "<leader>rr", desc = "add/remove rocket reaction" },
					react_laugh = { lhs = "<leader>rl", desc = "add/remove laugh reaction" },
					react_confused = { lhs = "<leader>rc", desc = "add/remove confused reaction" },
				},
				submit_win = {
					approve_review = { lhs = "<C-a>", desc = "approve review" },
					comment_review = { lhs = "<C-m>", desc = "comment review" },
					request_changes = { lhs = "<C-r>", desc = "request changes review" },
					close_review_tab = { lhs = "<C-c>", desc = "close review tab" },
				},
				review_diff = {
					submit_review = { lhs = "<leader>vs", desc = "submit review" },
					discard_review = { lhs = "<leader>vd", desc = "discard review" },
					add_review_comment = { lhs = "<leader>ca", desc = "add a new review comment" },
					add_review_suggestion = { lhs = "<leader>sa", desc = "add a new review suggestion" },
					focus_files = { lhs = "<leader>e", desc = "move focus to changed file panel" },
					toggle_files = { lhs = "<leader>b", desc = "toggle changed files panel" },
					next_thread = { lhs = "]t", desc = "move to next thread" },
					prev_thread = { lhs = "[t", desc = "move to previous thread" },
					select_next_entry = { lhs = "]q", desc = "move to next changed file" },
					select_prev_entry = { lhs = "[q", desc = "move to previous changed file" },
					select_first_entry = { lhs = "[Q", desc = "move to first changed file" },
					select_last_entry = { lhs = "]Q", desc = "move to last changed file" },
					close_review_tab = { lhs = "<C-c>", desc = "close review tab" },
					toggle_viewed = { lhs = "<leader><leader>", desc = "toggle viewer viewed state" },
					goto_file = { lhs = "gf", desc = "go to file" },
				},
				file_panel = {
					submit_review = { lhs = "<leader>vs", desc = "submit review" },
					discard_review = { lhs = "<leader>vd", desc = "discard review" },
					next_entry = { lhs = "j", desc = "move to next changed file" },
					prev_entry = { lhs = "k", desc = "move to previous changed file" },
					select_entry = { lhs = "<cr>", desc = "show selected changed file diffs" },
					refresh_files = { lhs = "R", desc = "refresh changed files panel" },
					focus_files = { lhs = "<leader>e", desc = "move focus to changed file panel" },
					toggle_files = { lhs = "<leader>b", desc = "toggle changed files panel" },
					select_next_entry = { lhs = "]q", desc = "move to next changed file" },
					select_prev_entry = { lhs = "[q", desc = "move to previous changed file" },
					select_first_entry = { lhs = "[Q", desc = "move to first changed file" },
					select_last_entry = { lhs = "]Q", desc = "move to last changed file" },
					close_review_tab = { lhs = "<C-c>", desc = "close review tab" },
					toggle_viewed = { lhs = "<leader><leader>", desc = "toggle viewer viewed state" },
				},
			},
		})
	end,
}
